server:
  port: 7001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tanglm4346/mall/tree/master/spring-could-demo/config-repo
          username: tlm434632
          password: tlm19921021
