server:
  port: 7001
spring:
  application:
    name: config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tanglm4346/mall.git
          username: tlm4346@126.com
          password: tlm19921021
          search-paths: spring-could-demo/config-repo
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/



management:
  endpoints:
    web:
      exposure:
        include: '*'
