server:
  port: 8001
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wx_product?characterEncoding=utf-8&amp;serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
mybatis:
  type-aliases-package: com.tlm.could.product.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/mapper/*Mapper.xml
logging:
  level:
    com.tlm.could.product.mapper: debug

